### ISSUE TITLE
Add Feature to Iterate Through Array Elements in ArcaneScript

### ISSUE THREAD

**Issue by thecloudcode** [Ghostfury73/ArcaneScript#1]
## Issue Description:
Feature Request:
Add the capability to iterate through array elements in ArcaneScript to print or access values using a for loop.

### Current Behavior:
Currently, there's no built-in functionality or syntax support for iterating through array elements directly in ArcaneScript. The existing for loop implementation does not seem to support accessing array elements correctly when using println array[i];.

### Expected Behavior:
Users should be able to initialize an array and iterate through its elements using a loop structure. For example:
array numbers[5] = {1, 2, 3, 4, 5};

for (i = 0; i < 5; i = i + 1;) {
    println numbers[i];
}

The output should display each element of the array as expected:
1
2
3
4
5

### Proposed Solution:
Implement or modify the interpreter/compiler to support iterating through arrays using indices, allowing for the use of numbers[i] syntax within loop structures. Ensure compatibility with println and print functions.

### Additional Notes:
This enhancement will improve the usability of ArcaneScript for array handling.
Test cases should be added to verify correct functionality across different loop types and array sizes.

Priority: Medium
Type: Feature Request

**Comment by thecloudcode** [comment]
Hi @amritrout , I have gone through your repo in detail, and would love to work on this issue. Can I continue forward?

**Comment by amritrout** [comment]
> Hi @amritrout , I have gone through your repo in detail, and would love to work on this issue. Can I continue forward?

@thecloudcode Nice find! Feel free to go ahead with the implementation. Let me know if you need any help along the way!

**Comment by thecloudcode** [comment]
Hi, @amritrout I have debugged this issue. Kindly check the PR, and let me know any further adjustments if required, under Hacktoberfest.
